import datetime

main_24: dict[str, type] = {
    "unit_id": int,
    "chl_id": int,
    "test_id": int,
    "seq_id": int,
    "cycle": int,
    "step_id": int,
    "step_type": int,
    "step_changecount": int,
    "work_type": int,
    "test_time": int,
    "test_vol": int,
    "test_cur": int,
    "test_ir": int,
    "test_tmp": int,
    "factor_capchg": int,
    "test_capchg": int,
    "factor_engchg": int,
    "test_engchg": int,
    "factor_capdchg": int,
    "test_capdchg": int,
    "factor_engdchg": int,
    "test_engdchg": int,
    "cur_step_range": int,
    "test_atime": datetime.datetime,
    "dataupdate": datetime.datetime,
}

aux_24: dict[str, type] = {
    "unit_id": int,
    "chl_id": int,
    "auxchl_id": int,
    "data_flag": int,
    "test_id": int,
    "seq_id": int,
    "cycle": int,
    "step_id": int,
    "step_type": int,
    "step_changecount": int,
    "work_type": int,
    "test_time": int,
    "test_vol": int,
    "test_cur": int,
    "test_ir": int,
    "test_tmp": int,
    "factor_capchg": int,
    "test_capchg": int,
    "factor_engchg": int,
    "test_engchg": int,
    "factor_capdchg": int,
    "test_capdchg": int,
    "factor_engdchg": int,
    "test_engdchg": int,
    "cur_step_range": int,
    "test_atime": datetime.datetime,
    "dataupdate": datetime.datetime,
}
